name: React

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  react-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies and build project
        working-directory: react-app
        run: |
          npm install --force
          npm run build
          
  react-test:
    runs-on: self-hosted
    needs: react-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies and build project
        working-directory: react-app
        run: |
          npm install --force
          npm run test
